runtime: python39 # Or python310, python311, etc.
entrypoint: streamlit run streamlit_app.py --server.port $PORT --server.enableCORS false --server.enableXsrfProtection false --server.headless true

instance_class: F1 

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  # Database Credentials (These are read by your streamlit_app.py)
  # DB_HOST is the Unix socket path provided by the Cloud SQL Proxy
  DB_HOST: "/cloudsql/crucial-citron-461315-t0:us-central1:streamlit-stosbx" 
  DB_DATABASE: "test"    # Your Cloud SQL Database Name
  DB_USER: "root"        # Your DB User
  DB_PASSWORD: "TrumpMick2024!!" # Your DB Password (ensure this is correct)
  DB_PORT: "" # Set to empty string or remove for Unix socket connection

  # APP_USERNAME and APP_PASSWORD are not strictly needed for this basic test,
  # but your deploy.yaml still tries to populate them, so keep them in GitHub secrets.
  APP_USERNAME: "admin" 
  APP_PASSWORD: "admin_secure_password"

# IMPORTANT: This line is crucial for App Engine to enable the proxy
cloud_sql_instances: crucial-citron-461315-t0:us-central1:streamlit-stosbx 